# Generated by Django 6.0.7 on 2026-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="Car", max_length=1000),
            preserve_default=False,
        ),
    ]
