# Generated by Django 6.0.7 on 2026-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_price",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
