# Generated by Django 6.0.7 on 2026-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0004_listing_active_listing_winner_alter_listing_creator_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.BooleanField(default=False),
        ),
    ]
